### ISSUE TITLE
Error when running make

### ISSUE THREAD

**Issue by orbitalchicken** [luxi78/joplin2obsidian#18]
build version: v0.2.1-10-g2010861
env CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags "-X main.Version=v0.2.1-10-g2010861" -o dist/joplin2obsidian_darwin_amd64
env: ‘go’: No such file or directory
make: *** [makefile:6: core] Error 127

**Comment by piotrek-k** [comment]
It seems you need to install go: https://go.dev/doc/install
